### ISSUE TITLE
unable to access 'https://github.com/home-assistant/hassio-addons/'

### ISSUE THREAD

**Issue by cpaucar3** [home-assistant/hassio-installer#7]
19-05-03 23:51:02 INFO (MainThread) [__main__] Initialize Hass.io setup
19-05-03 23:51:02 INFO (MainThread) [hassio.bootstrap] Create Home Assistant configuration folder /data/homeassistant
19-05-03 23:51:02 INFO (MainThread) [hassio.bootstrap] Create Hass.io SSL/TLS folder /data/ssl
19-05-03 23:51:02 INFO (MainThread) [hassio.bootstrap] Create Hass.io Add-on data folder /data/addons/data
19-05-03 23:51:02 INFO (MainThread) [hassio.bootstrap] Create Hass.io Add-on local repository folder /data/addons/local
19-05-03 23:51:02 INFO (MainThread) [hassio.bootstrap] Create Hass.io Add-on git repositories folder /data/addons/git
19-05-03 23:51:02 INFO (MainThread) [hassio.bootstrap] Create Hass.io temp folder /data/tmp
19-05-03 23:51:02 INFO (MainThread) [hassio.bootstrap] Create Hass.io backup folder /data/backup
19-05-03 23:51:02 INFO (MainThread) [hassio.bootstrap] Create Hass.io share folder /data/share
19-05-03 23:51:02 INFO (MainThread) [__main__] Setup HassIO
19-05-03 23:51:02 INFO (SyncWorker_0) [hassio.docker.supervisor] Attach to Supervisor homeassistant/amd64-hassio-supervisor with version 162
19-05-03 23:51:02 INFO (SyncWorker_0) [hassio.docker.supervisor] Connect Supervisor to Hass.io Network
19-05-03 23:51:02 INFO (MainThread) [hassio.utils.gdbus] Introspect org.freedesktop.systemd1 on /org/freedesktop/systemd1
19-05-03 23:51:02 INFO (MainThread) [hassio.utils.gdbus] Connect to dbus: org.freedesktop.systemd1 - /org/freedesktop/systemd1
19-05-03 23:51:02 INFO (MainThread) [hassio.utils.gdbus] Introspect org.freedesktop.hostname1 on /org/freedesktop/hostname1
19-05-03 23:51:02 INFO (MainThread) [hassio.utils.gdbus] Connect to dbus: org.freedesktop.hostname1 - /org/freedesktop/hostname1
19-05-03 23:51:02 INFO (MainThread) [hassio.utils.gdbus] Introspect de.pengutronix.rauc on /
19-05-03 23:51:02 ERROR (MainThread) [hassio.utils.gdbus] DBus return error: b'Error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name de.pengutronix.rauc was not provided by any .service files\n'
19-05-03 23:51:02 WARNING (MainThread) [hassio.dbus.rauc] Can't connect to rauc
19-05-03 23:51:02 INFO (MainThread) [hassio.host.info] Update local host information
19-05-03 23:51:02 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
19-05-03 23:51:02 INFO (MainThread) [hassio.host.services] Update service information
19-05-03 23:51:02 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
19-05-03 23:51:02 INFO (MainThread) [hassio.host.apparmor] Load AppArmor Profiles: {'hassio-supervisor'}
19-05-03 23:51:02 INFO (MainThread) [hassio.host.services] Reload local service hassio-apparmor.service
19-05-03 23:51:02 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.systemd1.Manager.ReloadOrRestartUnit on /org/freedesktop/systemd1
19-05-03 23:51:02 INFO (MainThread) [hassio.homeassistant] No Home Assistant Docker image homeassistant/qemux86-64-homeassistant found.
19-05-03 23:51:02 INFO (MainThread) [hassio.homeassistant] Setup HomeAssistant landingpage
19-05-03 23:51:02 INFO (SyncWorker_2) [hassio.docker.interface] Pull image homeassistant/qemux86-64-homeassistant tag landingpage.
19-05-03 23:51:03 INFO (SyncWorker_2) [hassio.docker.interface] Tag image homeassistant/qemux86-64-homeassistant with version landingpage as latest
19-05-03 23:51:03 INFO (MainThread) [hassio.addons.git] Clone add-on https://github.com/home-assistant/hassio-addons repository
19-05-03 23:51:03 INFO (MainThread) [hassio.addons.git] Clone add-on https://github.com/hassio-addons/repository repository
19-05-03 23:53:14 ERROR (MainThread) [hassio.addons.git] Can't clone https://github.com/home-assistant/hassio-addons repository: Cmd('git') failed due to: exit code(128)
  cmdline: git clone --depth=1 --recursive --shallow-submodules -v https://github.com/home-assistant/hassio-addons /data/addons/core
  stderr: 'Cloning into '/data/addons/core'...
fatal: unable to access 'https://github.com/home-assistant/hassio-addons/': Failed to connect to github.com port 443: Operation timed out
'.
19-05-03 23:53:14 ERROR (MainThread) [hassio.addons] Can't load from repository core
19-05-03 23:53:14 ERROR (MainThread) [hassio.addons.git] Can't clone https://github.com/hassio-addons/repository repository: Cmd('git') failed due to: exit code(128)
  cmdline: git clone --depth=1 --recursive --shallow-submodules -v https://github.com/hassio-addons/repository /data/addons/git/a0d7b954
  stderr: 'Cloning into '/data/addons/git/a0d7b954'...
fatal: unable to access 'https://github.com/hassio-addons/repository/': Failed to connect to github.com port 443: Operation timed out
'.
19-05-03 23:53:14 ERROR (MainThread) [hassio.addons] Can't load from repository https://github.com/hassio-addons/repository
19-05-03 23:53:14 INFO (MainThread) [hassio.addons] Load add-ons: 0 all - 0 new - 0 remove
19-05-03 23:53:14 INFO (MainThread) [hassio.updater] Fetch update data from https://s3.amazonaws.com/hassio-version/stable.json
19-05-03 23:53:24 WARNING (MainThread) [hassio.updater] Can't fetch versions from https://s3.amazonaws.com/hassio-version/stable.json: 
19-05-03 23:53:24 INFO (MainThread) [hassio.snapshots] Found 0 snapshot files
19-05-03 23:53:24 INFO (MainThread) [hassio.discovery] Load 0 messages
19-05-03 23:53:24 INFO (MainThread) [hassio.ingress] Load 0 ingress session
19-05-03 23:53:24 INFO (MainThread) [__main__] Run Hass.io
19-05-03 23:53:24 INFO (MainThread) [hassio.misc.dns] Start DNS port forwarding for host add-ons
19-05-03 23:53:24 INFO (MainThread) [hassio.supervisor] Update Supervisor to version None
19-05-03 23:53:24 INFO (SyncWorker_4) [hassio.docker.interface] Pull image homeassistant/amd64-hassio-supervisor tag None.
19-05-03 23:53:24 ERROR (SyncWorker_4) [hassio.docker.interface] Can't install homeassistant/amd64-hassio-supervisor:None -> 404 Client Error: Not Found ("manifest for homeassistant/amd64-hassio-supervisor:None not found").
19-05-03 23:53:24 ERROR (MainThread) [hassio.supervisor] Update of Hass.io fails!
19-05-03 23:53:24 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished coro=<HassIO.start() done, defined at /usr/local/lib/python3.7/site-packages/hassio/core.py:71> exception=SupervisorUpdateError()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/hassio/core.py", line 77, in start
    elif await self.sys_supervisor.update():
  File "/usr/local/lib/python3.7/site-packages/hassio/supervisor.py", line 115, in update
    raise SupervisorUpdateError() from None
hassio.exceptions.SupervisorUpdateError

**Comment by cpaucar3** [comment]
Solved it. It was a DNS configuration issue inside Docker. I added my Pi-hole as a primary server and OpenDNS as a secondary server in /etc/docker/daemon.json and it works now. Followed instructions from here: https://docs.docker.com/install/linux/linux-postinstall/
